=== EnzoBanchon/.............../banda.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
      "group": {
        "type": "string",
        "minLength": 2,
        "maxLength": 50
      },
      "foundation_year": {
        "type": "string",
        "format": "date"
      },
      "web": {
        "type": "string",
        "format": "uri"
      },
      "email": {
        "type": "string",
        "format": "email"
      },
      "description": {
        "type": "string",
        "minLength": 50,
        "maxLength": 500
      },
      "members": {
        "type": "array",
        "minItems": 2,
        "maxItems": 10,
        "uniqueItems": true,
        "items": {
          "type": "object",
          "properties": {
            "name": {"type": "string"},
            "age": {"type": "number", "minimum": 0, "maximum": 120}
          },
          "required": ["name", "age"]
        }
      },
      "albums": {
        "type": "array",
        "minItems": 1,
        "uniqueItems": true,
        "items": {
          "type": "object",
          "properties": {
            "name": {"type": "string"},
            "year": {"type": "string"},
            "sogs": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "nombre": {"type": "string"},
                  "length": {"type": "string", "format": "time"},
                  "hit": {"type": "boolean"}
                },
                "required": ["nombre", "length"]
              }
            }
          },
          "required": ["name", "year", "songs"]
        }
      },
      "concerts": {
        "type": "array",
        "minItems": 1,
        "maxItems": 20,
        "uniqueItems": true,
        "items": {"type": "string"}
      }
    },
    "required": ["group", "foundation_year", "web", "email", "description", "members", "albums", "concerts"]
}

=== EnzoBanchon/.............../banda.json
{
    "$schema": "./banda.schema.json",
    "group": "Aladino",
    "foundation_year": "1979-05-15",
    "web": "https://www.instagram.com/aladinoecuador/?hl=es",
    "email": "enzo.banchon@alumnos.upm.es",
    "description": "Más conocido como Aladino el Mago de la Rockola, o simplemente Aladino, es un cantante de rockola ecuatoriano, quien también se ha desempeñado como actor y presentador de televisión.",
    "members": [
        { 
            "name": "Billy Balseca",
            "age": 68
        },
        { 
            "name": "Naldo Campos",
            "age": 74
        },
        { 
            "name": "Roberto Calero",
            "age": 78
        }
    ],
    "albums": [
        { 
            "name": "Con clase A",   
            "year": "2021",
            "songs": [
                {
                    "nombre": "Penas",
                    "length": "4:14",
                    "hit": "true"
                },
                {
                    "nombre": "Mujer Bolera",
                    "length": "2:53",
                    "hit": "true"
                }
            ]
        }
    ],
    "concerts": [
        "Italia", 
        "Venezuela", 
        "Colombia", 
        "Perú"
    ]
}
